environments:
  local:
    ldap_servers:
      - "ldap://apps-ldap.corp.redhat.com:389"
    username: "uid=pco-deleted-users-query,ou=users,dc=redhat,dc=com"
    base_dn: "dc=redhat,dc=com"
    use_start_tls: true
    verify_ssl: false
    password_file: "~/.secrets/on-premise-asset-hub-secrets/ldap_password.txt"  # Will read password from file
    
  integration:
    ldap_servers:
      - "ldap://integration-ldap.corp.redhat.com:389"
    username: "uid=pco-deleted-users-query,ou=users,dc=redhat,dc=com"
    base_dn: "dc=redhat,dc=com"
    use_start_tls: true
    verify_ssl: false
    password_file: "~/.secrets/on-premise-asset-hub-secrets/ldap_password.txt"  # Will read password from file
    
  production:
    ldap_servers:
      - "ldaps://ldap.corp.redhat.com:636"
      - "ldaps://ldap2.corp.redhat.com:636"  # failover
    username: "uid=pco-deleted-users-query,ou=users,dc=redhat,dc=com"
    base_dn: "dc=redhat,dc=com"
    use_start_tls: false  # using ldaps
    verify_ssl: true      # verify certs in prod
    password_file: "~/.secrets/on-premise-asset-hub-secrets/ldap_password.txt"  # Will read password from file
